name: Compatibility Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    needs: test-package-install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
        platform:
          - { name: "aws", env: "poc" }
          - { name: "az", env: "avnet" }
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # only check if package will build correctly
      - name: Package Install
        run: scripts/package.sh

      # local install prep for next steps
      - name: Local Install
        run: scripts/local-build.sh

      - name: ${{ matrix.platform.name }} Login
        run: |
          if [ "${{ matrix.platform.name }}" = "aws" ]; then
            iotconnect-cli configure -pf ${{ matrix.platform.name }} -e ${{ matrix.platform.env }} -u "${{ secrets.IOTC_AWS_USER }}" -p "${{ secrets.IOTC_AWS_PASS }}" -s "${{ secrets.IOTC_AWS_SKEY }}"
          elif [ "${{ matrix.platform.name }}" = "az" ]; then
            iotconnect-cli configure -pf ${{ matrix.platform.name }} -e ${{ matrix.platform.env }} -u "${{ secrets.IOTC_AZ_USER }}" -p "${{ secrets.IOTC_AZ_PASS }}" -s "${{ secrets.IOTC_AZ_SKEY }}"
          fi

      - name: ${{ matrix.platform.name }} CLI Test
        run: iotconnect-cli --help && iotconnect-cli --refresh

      - name: ${{ matrix.platform.name }} Run Tests
        run: scripts/run-tests.sh